common: &default_settings
  # For heroku Review Apps, the HEROKU_BRANCH will be set and we can construct the domain using the
  # injected HEROKU_APP_NAME. Note that we check for the HEROKU_BRANCH variable and don't simply
  # look for the HEROKU_APP_NAME in case Dyno Metadata is enabled on a non-review app:
  # https://devcenter.heroku.com/articles/dyno-metadata
  # TODO:
  # Getting errors during compile assets with the belowsyntax. Since we don't have review apps working yet
  # just commenting out the stuff to try and set the domain properly for a review app. We'll have to fix
  # this up when we get there.
  #domain: <%= ENV['HEROKU_BRANCH'].nil? ? ENV['DOMAIN'] : "#{ENV['HEROKU_APP_NAME']}.herokuapp.com" %>
  domain: <%= ENV['DOMAIN'] %>
  ssl: true

development:
  <<: *default_settings
  ssl: false

test:
  <<: *default_settings
  domain: localhost
  ssl: false

staging:
  <<: *default_settings

production:
  <<: *default_settings

