common: &default_settings
  storage: s3

development:
  <<: *default_settings

test:
  <<: *default_settings
  storage: local
  path_prefix: tmp/files

staging:
  <<: *default_settings

production:
  <<: *default_settings
